name = 'alt:V Server'
port = 7788
players = 128
# password = 'ultra-password'
announce = false
# token = 'YOUR_TOKEN'
language = 'en'
modules = ['csharp-module', 'js-module', 'js-bytecode-module']
resources = ['chat', 'freeroam']